/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ocms.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Contact service. Represents a row in the &quot;CM_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ocms.course.model.impl.ContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ocms.course.model.impl.ContactImpl}.
 * </p>
 *
 * @author doraraj
 * @see Contact
 * @see com.ocms.course.model.impl.ContactImpl
 * @see com.ocms.course.model.impl.ContactModelImpl
 * @generated
 */
public interface ContactModel extends BaseModel<Contact>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact model instance should use the {@link Contact} interface instead.
	 */

	/**
	 * Returns the primary key of this contact.
	 *
	 * @return the primary key of this contact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact.
	 *
	 * @param primaryKey the primary key of this contact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the contact ID of this contact.
	 *
	 * @return the contact ID of this contact
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this contact.
	 *
	 * @param contactId the contact ID of this contact
	 */
	public void setContactId(long contactId);

	/**
	 * Returns the group ID of this contact.
	 *
	 * @return the group ID of this contact
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this contact.
	 *
	 * @param groupId the group ID of this contact
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this contact.
	 *
	 * @return the company ID of this contact
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this contact.
	 *
	 * @param companyId the company ID of this contact
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contact.
	 *
	 * @return the user ID of this contact
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this contact.
	 *
	 * @param userId the user ID of this contact
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contact.
	 *
	 * @return the user uuid of this contact
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this contact.
	 *
	 * @param userUuid the user uuid of this contact
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this contact.
	 *
	 * @return the user name of this contact
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this contact.
	 *
	 * @param userName the user name of this contact
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this contact.
	 *
	 * @return the create date of this contact
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this contact.
	 *
	 * @param createDate the create date of this contact
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contact.
	 *
	 * @return the modified date of this contact
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contact.
	 *
	 * @param modifiedDate the modified date of this contact
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the contact type of this contact.
	 *
	 * @return the contact type of this contact
	 */
	@AutoEscape
	public String getContactType();

	/**
	 * Sets the contact type of this contact.
	 *
	 * @param contactType the contact type of this contact
	 */
	public void setContactType(String contactType);

	/**
	 * Returns the contact name of this contact.
	 *
	 * @return the contact name of this contact
	 */
	@AutoEscape
	public String getContactName();

	/**
	 * Sets the contact name of this contact.
	 *
	 * @param contactName the contact name of this contact
	 */
	public void setContactName(String contactName);

	/**
	 * Returns the address line1 of this contact.
	 *
	 * @return the address line1 of this contact
	 */
	@AutoEscape
	public String getAddressLine1();

	/**
	 * Sets the address line1 of this contact.
	 *
	 * @param addressLine1 the address line1 of this contact
	 */
	public void setAddressLine1(String addressLine1);

	/**
	 * Returns the address line2 of this contact.
	 *
	 * @return the address line2 of this contact
	 */
	@AutoEscape
	public String getAddressLine2();

	/**
	 * Sets the address line2 of this contact.
	 *
	 * @param addressLine2 the address line2 of this contact
	 */
	public void setAddressLine2(String addressLine2);

	/**
	 * Returns the city of this contact.
	 *
	 * @return the city of this contact
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this contact.
	 *
	 * @param city the city of this contact
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this contact.
	 *
	 * @return the state of this contact
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this contact.
	 *
	 * @param state the state of this contact
	 */
	public void setState(String state);

	/**
	 * Returns the region of this contact.
	 *
	 * @return the region of this contact
	 */
	@AutoEscape
	public String getRegion();

	/**
	 * Sets the region of this contact.
	 *
	 * @param region the region of this contact
	 */
	public void setRegion(String region);

	/**
	 * Returns the zip of this contact.
	 *
	 * @return the zip of this contact
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this contact.
	 *
	 * @param zip the zip of this contact
	 */
	public void setZip(String zip);

	/**
	 * Returns the phone of this contact.
	 *
	 * @return the phone of this contact
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this contact.
	 *
	 * @param phone the phone of this contact
	 */
	public void setPhone(String phone);

	/**
	 * Returns the fax of this contact.
	 *
	 * @return the fax of this contact
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this contact.
	 *
	 * @param fax the fax of this contact
	 */
	public void setFax(String fax);

	/**
	 * Returns the email of this contact.
	 *
	 * @return the email of this contact
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this contact.
	 *
	 * @param email the email of this contact
	 */
	public void setEmail(String email);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Contact contact);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Contact> toCacheModel();

	@Override
	public Contact toEscapedModel();

	@Override
	public Contact toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}