/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ocms.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CourseSeries service. Represents a row in the &quot;CM_CourseSeries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ocms.course.model.impl.CourseSeriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ocms.course.model.impl.CourseSeriesImpl}.
 * </p>
 *
 * @author doraraj
 * @see CourseSeries
 * @see com.ocms.course.model.impl.CourseSeriesImpl
 * @see com.ocms.course.model.impl.CourseSeriesModelImpl
 * @generated
 */
public interface CourseSeriesModel extends BaseModel<CourseSeries>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course series model instance should use the {@link CourseSeries} interface instead.
	 */

	/**
	 * Returns the primary key of this course series.
	 *
	 * @return the primary key of this course series
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course series.
	 *
	 * @param primaryKey the primary key of this course series
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the course series ID of this course series.
	 *
	 * @return the course series ID of this course series
	 */
	public long getCourseSeriesId();

	/**
	 * Sets the course series ID of this course series.
	 *
	 * @param courseSeriesId the course series ID of this course series
	 */
	public void setCourseSeriesId(long courseSeriesId);

	/**
	 * Returns the group ID of this course series.
	 *
	 * @return the group ID of this course series
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this course series.
	 *
	 * @param groupId the group ID of this course series
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this course series.
	 *
	 * @return the company ID of this course series
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this course series.
	 *
	 * @param companyId the company ID of this course series
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this course series.
	 *
	 * @return the user ID of this course series
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this course series.
	 *
	 * @param userId the user ID of this course series
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course series.
	 *
	 * @return the user uuid of this course series
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this course series.
	 *
	 * @param userUuid the user uuid of this course series
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this course series.
	 *
	 * @return the user name of this course series
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this course series.
	 *
	 * @param userName the user name of this course series
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this course series.
	 *
	 * @return the create date of this course series
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this course series.
	 *
	 * @param createDate the create date of this course series
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course series.
	 *
	 * @return the modified date of this course series
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course series.
	 *
	 * @param modifiedDate the modified date of this course series
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the course ID of this course series.
	 *
	 * @return the course ID of this course series
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course series.
	 *
	 * @param courseId the course ID of this course series
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the location ID of this course series.
	 *
	 * @return the location ID of this course series
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this course series.
	 *
	 * @param locationId the location ID of this course series
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the type of this course series.
	 *
	 * @return the type of this course series
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this course series.
	 *
	 * @param type the type of this course series
	 */
	public void setType(String type);

	/**
	 * Returns the start date of this course series.
	 *
	 * @return the start date of this course series
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this course series.
	 *
	 * @param startDate the start date of this course series
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this course series.
	 *
	 * @return the end date of this course series
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this course series.
	 *
	 * @param endDate the end date of this course series
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the publishing status of this course series.
	 *
	 * @return the publishing status of this course series
	 */
	@AutoEscape
	public String getPublishingStatus();

	/**
	 * Sets the publishing status of this course series.
	 *
	 * @param publishingStatus the publishing status of this course series
	 */
	public void setPublishingStatus(String publishingStatus);

	/**
	 * Returns the max no stud reg of this course series.
	 *
	 * @return the max no stud reg of this course series
	 */
	public long getMaxNoStudReg();

	/**
	 * Sets the max no stud reg of this course series.
	 *
	 * @param maxNoStudReg the max no stud reg of this course series
	 */
	public void setMaxNoStudReg(long maxNoStudReg);

	/**
	 * Returns the series count of this course series.
	 *
	 * @return the series count of this course series
	 */
	public long getSeriesCount();

	/**
	 * Sets the series count of this course series.
	 *
	 * @param seriesCount the series count of this course series
	 */
	public void setSeriesCount(long seriesCount);

	/**
	 * Returns the course series code of this course series.
	 *
	 * @return the course series code of this course series
	 */
	@AutoEscape
	public String getCourseSeriesCode();

	/**
	 * Sets the course series code of this course series.
	 *
	 * @param courseSeriesCode the course series code of this course series
	 */
	public void setCourseSeriesCode(String courseSeriesCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CourseSeries courseSeries);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CourseSeries> toCacheModel();

	@Override
	public CourseSeries toEscapedModel();

	@Override
	public CourseSeries toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}