/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ocms.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Event service. Represents a row in the &quot;CM_Event&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ocms.course.model.impl.EventModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ocms.course.model.impl.EventImpl}.
 * </p>
 *
 * @author doraraj
 * @see Event
 * @see com.ocms.course.model.impl.EventImpl
 * @see com.ocms.course.model.impl.EventModelImpl
 * @generated
 */
public interface EventModel extends BaseModel<Event>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event model instance should use the {@link Event} interface instead.
	 */

	/**
	 * Returns the primary key of this event.
	 *
	 * @return the primary key of this event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event.
	 *
	 * @param primaryKey the primary key of this event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the event ID of this event.
	 *
	 * @return the event ID of this event
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this event.
	 *
	 * @param eventId the event ID of this event
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the event name of this event.
	 *
	 * @return the event name of this event
	 */
	@AutoEscape
	public String getEventName();

	/**
	 * Sets the event name of this event.
	 *
	 * @param eventName the event name of this event
	 */
	public void setEventName(String eventName);

	/**
	 * Returns the course code of this event.
	 *
	 * @return the course code of this event
	 */
	@AutoEscape
	public String getCourseCode();

	/**
	 * Sets the course code of this event.
	 *
	 * @param courseCode the course code of this event
	 */
	public void setCourseCode(String courseCode);

	/**
	 * Returns the location code of this event.
	 *
	 * @return the location code of this event
	 */
	@AutoEscape
	public String getLocationCode();

	/**
	 * Sets the location code of this event.
	 *
	 * @param locationCode the location code of this event
	 */
	public void setLocationCode(String locationCode);

	/**
	 * Returns the start date of this event.
	 *
	 * @return the start date of this event
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this event.
	 *
	 * @param startDate the start date of this event
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the group ID of this event.
	 *
	 * @return the group ID of this event
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this event.
	 *
	 * @param groupId the group ID of this event
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this event.
	 *
	 * @return the company ID of this event
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this event.
	 *
	 * @param companyId the company ID of this event
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this event.
	 *
	 * @return the user ID of this event
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this event.
	 *
	 * @param userId the user ID of this event
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this event.
	 *
	 * @return the user uuid of this event
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this event.
	 *
	 * @param userUuid the user uuid of this event
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this event.
	 *
	 * @return the user name of this event
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this event.
	 *
	 * @param userName the user name of this event
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this event.
	 *
	 * @return the create date of this event
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this event.
	 *
	 * @param createDate the create date of this event
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this event.
	 *
	 * @return the modified date of this event
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this event.
	 *
	 * @param modifiedDate the modified date of this event
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the end date of this event.
	 *
	 * @return the end date of this event
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this event.
	 *
	 * @param endDate the end date of this event
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the flag of this event.
	 *
	 * @return the flag of this event
	 */
	public int getFlag();

	/**
	 * Sets the flag of this event.
	 *
	 * @param flag the flag of this event
	 */
	public void setFlag(int flag);

	/**
	 * Returns the course ID of this event.
	 *
	 * @return the course ID of this event
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this event.
	 *
	 * @param courseId the course ID of this event
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the location ID of this event.
	 *
	 * @return the location ID of this event
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this event.
	 *
	 * @param locationId the location ID of this event
	 */
	public void setLocationId(long locationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Event event);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Event> toCacheModel();

	@Override
	public Event toEscapedModel();

	@Override
	public Event toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}