/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ocms.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StudentRegistration service. Represents a row in the &quot;CM_StudentRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ocms.course.model.impl.StudentRegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ocms.course.model.impl.StudentRegistrationImpl}.
 * </p>
 *
 * @author doraraj
 * @see StudentRegistration
 * @see com.ocms.course.model.impl.StudentRegistrationImpl
 * @see com.ocms.course.model.impl.StudentRegistrationModelImpl
 * @generated
 */
public interface StudentRegistrationModel extends BaseModel<StudentRegistration>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student registration model instance should use the {@link StudentRegistration} interface instead.
	 */

	/**
	 * Returns the primary key of this student registration.
	 *
	 * @return the primary key of this student registration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student registration.
	 *
	 * @param primaryKey the primary key of this student registration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the stud reg ID of this student registration.
	 *
	 * @return the stud reg ID of this student registration
	 */
	public long getStudRegId();

	/**
	 * Sets the stud reg ID of this student registration.
	 *
	 * @param studRegId the stud reg ID of this student registration
	 */
	public void setStudRegId(long studRegId);

	/**
	 * Returns the group ID of this student registration.
	 *
	 * @return the group ID of this student registration
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this student registration.
	 *
	 * @param groupId the group ID of this student registration
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this student registration.
	 *
	 * @return the company ID of this student registration
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this student registration.
	 *
	 * @param companyId the company ID of this student registration
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this student registration.
	 *
	 * @return the user ID of this student registration
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this student registration.
	 *
	 * @param userId the user ID of this student registration
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this student registration.
	 *
	 * @return the user uuid of this student registration
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this student registration.
	 *
	 * @param userUuid the user uuid of this student registration
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this student registration.
	 *
	 * @return the user name of this student registration
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this student registration.
	 *
	 * @param userName the user name of this student registration
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this student registration.
	 *
	 * @return the create date of this student registration
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this student registration.
	 *
	 * @param createDate the create date of this student registration
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this student registration.
	 *
	 * @return the modified date of this student registration
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this student registration.
	 *
	 * @param modifiedDate the modified date of this student registration
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the memo of this student registration.
	 *
	 * @return the memo of this student registration
	 */
	@AutoEscape
	public String getMemo();

	/**
	 * Sets the memo of this student registration.
	 *
	 * @param memo the memo of this student registration
	 */
	public void setMemo(String memo);

	/**
	 * Returns the stud reg status of this student registration.
	 *
	 * @return the stud reg status of this student registration
	 */
	@AutoEscape
	public String getStudRegStatus();

	/**
	 * Sets the stud reg status of this student registration.
	 *
	 * @param studRegStatus the stud reg status of this student registration
	 */
	public void setStudRegStatus(String studRegStatus);

	/**
	 * Returns the advisor orig of this student registration.
	 *
	 * @return the advisor orig of this student registration
	 */
	@AutoEscape
	public String getAdvisorOrig();

	/**
	 * Sets the advisor orig of this student registration.
	 *
	 * @param advisorOrig the advisor orig of this student registration
	 */
	public void setAdvisorOrig(String advisorOrig);

	/**
	 * Returns the advisor reg of this student registration.
	 *
	 * @return the advisor reg of this student registration
	 */
	@AutoEscape
	public String getAdvisorReg();

	/**
	 * Sets the advisor reg of this student registration.
	 *
	 * @param advisorReg the advisor reg of this student registration
	 */
	public void setAdvisorReg(String advisorReg);

	/**
	 * Returns the course package ID of this student registration.
	 *
	 * @return the course package ID of this student registration
	 */
	public long getCoursePackageId();

	/**
	 * Sets the course package ID of this student registration.
	 *
	 * @param coursePackageId the course package ID of this student registration
	 */
	public void setCoursePackageId(long coursePackageId);

	/**
	 * Returns the discount ID of this student registration.
	 *
	 * @return the discount ID of this student registration
	 */
	public long getDiscountId();

	/**
	 * Sets the discount ID of this student registration.
	 *
	 * @param discountId the discount ID of this student registration
	 */
	public void setDiscountId(long discountId);

	/**
	 * Returns the comm method of this student registration.
	 *
	 * @return the comm method of this student registration
	 */
	@AutoEscape
	public String getCommMethod();

	/**
	 * Sets the comm method of this student registration.
	 *
	 * @param commMethod the comm method of this student registration
	 */
	public void setCommMethod(String commMethod);

	/**
	 * Returns the notes of this student registration.
	 *
	 * @return the notes of this student registration
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this student registration.
	 *
	 * @param notes the notes of this student registration
	 */
	public void setNotes(String notes);

	/**
	 * Returns the currency of this student registration.
	 *
	 * @return the currency of this student registration
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this student registration.
	 *
	 * @param currency the currency of this student registration
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the tax of this student registration.
	 *
	 * @return the tax of this student registration
	 */
	public long getTax();

	/**
	 * Sets the tax of this student registration.
	 *
	 * @param tax the tax of this student registration
	 */
	public void setTax(long tax);

	/**
	 * Returns the auto charge of this student registration.
	 *
	 * @return the auto charge of this student registration
	 */
	@AutoEscape
	public String getAutoCharge();

	/**
	 * Sets the auto charge of this student registration.
	 *
	 * @param autoCharge the auto charge of this student registration
	 */
	public void setAutoCharge(String autoCharge);

	/**
	 * Returns the currency paid of this student registration.
	 *
	 * @return the currency paid of this student registration
	 */
	@AutoEscape
	public String getCurrencyPaid();

	/**
	 * Sets the currency paid of this student registration.
	 *
	 * @param currencyPaid the currency paid of this student registration
	 */
	public void setCurrencyPaid(String currencyPaid);

	/**
	 * Returns the exchange rate of this student registration.
	 *
	 * @return the exchange rate of this student registration
	 */
	public long getExchangeRate();

	/**
	 * Sets the exchange rate of this student registration.
	 *
	 * @param exchangeRate the exchange rate of this student registration
	 */
	public void setExchangeRate(long exchangeRate);

	/**
	 * Returns the contact ID of this student registration.
	 *
	 * @return the contact ID of this student registration
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this student registration.
	 *
	 * @param contactId the contact ID of this student registration
	 */
	public void setContactId(long contactId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StudentRegistration studentRegistration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StudentRegistration> toCacheModel();

	@Override
	public StudentRegistration toEscapedModel();

	@Override
	public StudentRegistration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}