/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ocms.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaxDetails service. Represents a row in the &quot;CM_TaxDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ocms.course.model.impl.TaxDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ocms.course.model.impl.TaxDetailsImpl}.
 * </p>
 *
 * @author doraraj
 * @see TaxDetails
 * @see com.ocms.course.model.impl.TaxDetailsImpl
 * @see com.ocms.course.model.impl.TaxDetailsModelImpl
 * @generated
 */
public interface TaxDetailsModel extends BaseModel<TaxDetails>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tax details model instance should use the {@link TaxDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this tax details.
	 *
	 * @return the primary key of this tax details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tax details.
	 *
	 * @param primaryKey the primary key of this tax details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tax details ID of this tax details.
	 *
	 * @return the tax details ID of this tax details
	 */
	public long getTaxDetailsId();

	/**
	 * Sets the tax details ID of this tax details.
	 *
	 * @param taxDetailsId the tax details ID of this tax details
	 */
	public void setTaxDetailsId(long taxDetailsId);

	/**
	 * Returns the group ID of this tax details.
	 *
	 * @return the group ID of this tax details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tax details.
	 *
	 * @param groupId the group ID of this tax details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tax details.
	 *
	 * @return the company ID of this tax details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tax details.
	 *
	 * @param companyId the company ID of this tax details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tax details.
	 *
	 * @return the user ID of this tax details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tax details.
	 *
	 * @param userId the user ID of this tax details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tax details.
	 *
	 * @return the user uuid of this tax details
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tax details.
	 *
	 * @param userUuid the user uuid of this tax details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tax details.
	 *
	 * @return the user name of this tax details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tax details.
	 *
	 * @param userName the user name of this tax details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tax details.
	 *
	 * @return the create date of this tax details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tax details.
	 *
	 * @param createDate the create date of this tax details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tax details.
	 *
	 * @return the modified date of this tax details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tax details.
	 *
	 * @param modifiedDate the modified date of this tax details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the country of this tax details.
	 *
	 * @return the country of this tax details
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this tax details.
	 *
	 * @param country the country of this tax details
	 */
	public void setCountry(String country);

	/**
	 * Returns the tax type ID of this tax details.
	 *
	 * @return the tax type ID of this tax details
	 */
	public long getTaxTypeId();

	/**
	 * Sets the tax type ID of this tax details.
	 *
	 * @param taxTypeId the tax type ID of this tax details
	 */
	public void setTaxTypeId(long taxTypeId);

	/**
	 * Returns the effective from date of this tax details.
	 *
	 * @return the effective from date of this tax details
	 */
	public Date getEffectiveFromDate();

	/**
	 * Sets the effective from date of this tax details.
	 *
	 * @param effectiveFromDate the effective from date of this tax details
	 */
	public void setEffectiveFromDate(Date effectiveFromDate);

	/**
	 * Returns the effective to date of this tax details.
	 *
	 * @return the effective to date of this tax details
	 */
	public Date getEffectiveToDate();

	/**
	 * Sets the effective to date of this tax details.
	 *
	 * @param effectiveToDate the effective to date of this tax details
	 */
	public void setEffectiveToDate(Date effectiveToDate);

	/**
	 * Returns the active of this tax details.
	 *
	 * @return the active of this tax details
	 */
	public int getActive();

	/**
	 * Sets the active of this tax details.
	 *
	 * @param active the active of this tax details
	 */
	public void setActive(int active);

	/**
	 * Returns the tax percent of this tax details.
	 *
	 * @return the tax percent of this tax details
	 */
	public int getTaxPercent();

	/**
	 * Sets the tax percent of this tax details.
	 *
	 * @param taxPercent the tax percent of this tax details
	 */
	public void setTaxPercent(int taxPercent);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaxDetails taxDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaxDetails> toCacheModel();

	@Override
	public TaxDetails toEscapedModel();

	@Override
	public TaxDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}