/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ocms.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaxTypes service. Represents a row in the &quot;CM_TaxTypes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ocms.course.model.impl.TaxTypesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ocms.course.model.impl.TaxTypesImpl}.
 * </p>
 *
 * @author doraraj
 * @see TaxTypes
 * @see com.ocms.course.model.impl.TaxTypesImpl
 * @see com.ocms.course.model.impl.TaxTypesModelImpl
 * @generated
 */
public interface TaxTypesModel extends BaseModel<TaxTypes>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tax types model instance should use the {@link TaxTypes} interface instead.
	 */

	/**
	 * Returns the primary key of this tax types.
	 *
	 * @return the primary key of this tax types
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tax types.
	 *
	 * @param primaryKey the primary key of this tax types
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tax types ID of this tax types.
	 *
	 * @return the tax types ID of this tax types
	 */
	public long getTaxTypesId();

	/**
	 * Sets the tax types ID of this tax types.
	 *
	 * @param taxTypesId the tax types ID of this tax types
	 */
	public void setTaxTypesId(long taxTypesId);

	/**
	 * Returns the group ID of this tax types.
	 *
	 * @return the group ID of this tax types
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tax types.
	 *
	 * @param groupId the group ID of this tax types
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tax types.
	 *
	 * @return the company ID of this tax types
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tax types.
	 *
	 * @param companyId the company ID of this tax types
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tax types.
	 *
	 * @return the user ID of this tax types
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tax types.
	 *
	 * @param userId the user ID of this tax types
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tax types.
	 *
	 * @return the user uuid of this tax types
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tax types.
	 *
	 * @param userUuid the user uuid of this tax types
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tax types.
	 *
	 * @return the user name of this tax types
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tax types.
	 *
	 * @param userName the user name of this tax types
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tax types.
	 *
	 * @return the create date of this tax types
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tax types.
	 *
	 * @param createDate the create date of this tax types
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tax types.
	 *
	 * @return the modified date of this tax types
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tax types.
	 *
	 * @param modifiedDate the modified date of this tax types
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tax name of this tax types.
	 *
	 * @return the tax name of this tax types
	 */
	@AutoEscape
	public String getTaxName();

	/**
	 * Sets the tax name of this tax types.
	 *
	 * @param taxName the tax name of this tax types
	 */
	public void setTaxName(String taxName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaxTypes taxTypes);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaxTypes> toCacheModel();

	@Override
	public TaxTypes toEscapedModel();

	@Override
	public TaxTypes toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}