/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ocms.course.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.ocms.course.model.TaxTypes;
import com.ocms.course.model.TaxTypesModel;
import com.ocms.course.model.TaxTypesSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TaxTypes service. Represents a row in the &quot;CM_TaxTypes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ocms.course.model.TaxTypesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaxTypesImpl}.
 * </p>
 *
 * @author doraraj
 * @see TaxTypesImpl
 * @see com.ocms.course.model.TaxTypes
 * @see com.ocms.course.model.TaxTypesModel
 * @generated
 */
@JSON(strict = true)
public class TaxTypesModelImpl extends BaseModelImpl<TaxTypes>
	implements TaxTypesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tax types model instance should use the {@link com.ocms.course.model.TaxTypes} interface instead.
	 */
	public static final String TABLE_NAME = "CM_TaxTypes";
	public static final Object[][] TABLE_COLUMNS = {
			{ "taxTypesId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "taxName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CM_TaxTypes (taxTypesId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,taxName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CM_TaxTypes";
	public static final String ORDER_BY_JPQL = " ORDER BY taxTypes.taxTypesId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CM_TaxTypes.taxTypesId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ocms.course.model.TaxTypes"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ocms.course.model.TaxTypes"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ocms.course.model.TaxTypes"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long TAXTYPESID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TaxTypes toModel(TaxTypesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TaxTypes model = new TaxTypesImpl();

		model.setTaxTypesId(soapModel.getTaxTypesId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTaxName(soapModel.getTaxName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TaxTypes> toModels(TaxTypesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TaxTypes> models = new ArrayList<TaxTypes>(soapModels.length);

		for (TaxTypesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ocms.course.model.TaxTypes"));

	public TaxTypesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taxTypesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaxTypesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taxTypesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaxTypes.class;
	}

	@Override
	public String getModelClassName() {
		return TaxTypes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("taxTypesId", getTaxTypesId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("taxName", getTaxName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long taxTypesId = (Long)attributes.get("taxTypesId");

		if (taxTypesId != null) {
			setTaxTypesId(taxTypesId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String taxName = (String)attributes.get("taxName");

		if (taxName != null) {
			setTaxName(taxName);
		}
	}

	@JSON
	@Override
	public long getTaxTypesId() {
		return _taxTypesId;
	}

	@Override
	public void setTaxTypesId(long taxTypesId) {
		_columnBitmask |= TAXTYPESID_COLUMN_BITMASK;

		if (!_setOriginalTaxTypesId) {
			_setOriginalTaxTypesId = true;

			_originalTaxTypesId = _taxTypesId;
		}

		_taxTypesId = taxTypesId;
	}

	public long getOriginalTaxTypesId() {
		return _originalTaxTypesId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTaxName() {
		if (_taxName == null) {
			return StringPool.BLANK;
		}
		else {
			return _taxName;
		}
	}

	@Override
	public void setTaxName(String taxName) {
		_taxName = taxName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TaxTypes.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaxTypes toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TaxTypes)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaxTypesImpl taxTypesImpl = new TaxTypesImpl();

		taxTypesImpl.setTaxTypesId(getTaxTypesId());
		taxTypesImpl.setGroupId(getGroupId());
		taxTypesImpl.setCompanyId(getCompanyId());
		taxTypesImpl.setUserId(getUserId());
		taxTypesImpl.setUserName(getUserName());
		taxTypesImpl.setCreateDate(getCreateDate());
		taxTypesImpl.setModifiedDate(getModifiedDate());
		taxTypesImpl.setTaxName(getTaxName());

		taxTypesImpl.resetOriginalValues();

		return taxTypesImpl;
	}

	@Override
	public int compareTo(TaxTypes taxTypes) {
		long primaryKey = taxTypes.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TaxTypes)) {
			return false;
		}

		TaxTypes taxTypes = (TaxTypes)obj;

		long primaryKey = taxTypes.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TaxTypesModelImpl taxTypesModelImpl = this;

		taxTypesModelImpl._originalTaxTypesId = taxTypesModelImpl._taxTypesId;

		taxTypesModelImpl._setOriginalTaxTypesId = false;

		taxTypesModelImpl._originalGroupId = taxTypesModelImpl._groupId;

		taxTypesModelImpl._setOriginalGroupId = false;

		taxTypesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaxTypes> toCacheModel() {
		TaxTypesCacheModel taxTypesCacheModel = new TaxTypesCacheModel();

		taxTypesCacheModel.taxTypesId = getTaxTypesId();

		taxTypesCacheModel.groupId = getGroupId();

		taxTypesCacheModel.companyId = getCompanyId();

		taxTypesCacheModel.userId = getUserId();

		taxTypesCacheModel.userName = getUserName();

		String userName = taxTypesCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			taxTypesCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			taxTypesCacheModel.createDate = createDate.getTime();
		}
		else {
			taxTypesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			taxTypesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			taxTypesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		taxTypesCacheModel.taxName = getTaxName();

		String taxName = taxTypesCacheModel.taxName;

		if ((taxName != null) && (taxName.length() == 0)) {
			taxTypesCacheModel.taxName = null;
		}

		return taxTypesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{taxTypesId=");
		sb.append(getTaxTypesId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", taxName=");
		sb.append(getTaxName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.ocms.course.model.TaxTypes");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>taxTypesId</column-name><column-value><![CDATA[");
		sb.append(getTaxTypesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taxName</column-name><column-value><![CDATA[");
		sb.append(getTaxName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TaxTypes.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TaxTypes.class
		};
	private long _taxTypesId;
	private long _originalTaxTypesId;
	private boolean _setOriginalTaxTypesId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _taxName;
	private long _columnBitmask;
	private TaxTypes _escapedModel;
}