/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ocms.course.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.ocms.course.model.CoursePackage;
import com.ocms.course.model.CoursePackageModel;
import com.ocms.course.model.CoursePackageSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CoursePackage service. Represents a row in the &quot;CM_CoursePackage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ocms.course.model.CoursePackageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CoursePackageImpl}.
 * </p>
 *
 * @author doraraj
 * @see CoursePackageImpl
 * @see com.ocms.course.model.CoursePackage
 * @see com.ocms.course.model.CoursePackageModel
 * @generated
 */
@JSON(strict = true)
public class CoursePackageModelImpl extends BaseModelImpl<CoursePackage>
	implements CoursePackageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course package model instance should use the {@link com.ocms.course.model.CoursePackage} interface instead.
	 */
	public static final String TABLE_NAME = "CM_CoursePackage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "coursePackageId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "code_", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table CM_CoursePackage (coursePackageId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,code_ VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table CM_CoursePackage";
	public static final String ORDER_BY_JPQL = " ORDER BY coursePackage.coursePackageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CM_CoursePackage.coursePackageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ocms.course.model.CoursePackage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ocms.course.model.CoursePackage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ocms.course.model.CoursePackage"),
			true);
	public static long COURSEPACKAGEID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long NAME_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CoursePackage toModel(CoursePackageSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CoursePackage model = new CoursePackageImpl();

		model.setCoursePackageId(soapModel.getCoursePackageId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setCode(soapModel.getCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CoursePackage> toModels(CoursePackageSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CoursePackage> models = new ArrayList<CoursePackage>(soapModels.length);

		for (CoursePackageSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ocms.course.model.CoursePackage"));

	public CoursePackageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _coursePackageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCoursePackageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _coursePackageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CoursePackage.class;
	}

	@Override
	public String getModelClassName() {
		return CoursePackage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("coursePackageId", getCoursePackageId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("code", getCode());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long coursePackageId = (Long)attributes.get("coursePackageId");

		if (coursePackageId != null) {
			setCoursePackageId(coursePackageId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String code = (String)attributes.get("code");

		if (code != null) {
			setCode(code);
		}
	}

	@JSON
	@Override
	public long getCoursePackageId() {
		return _coursePackageId;
	}

	@Override
	public void setCoursePackageId(long coursePackageId) {
		_columnBitmask |= COURSEPACKAGEID_COLUMN_BITMASK;

		if (!_setOriginalCoursePackageId) {
			_setOriginalCoursePackageId = true;

			_originalCoursePackageId = _coursePackageId;
		}

		_coursePackageId = coursePackageId;
	}

	public long getOriginalCoursePackageId() {
		return _originalCoursePackageId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return StringPool.BLANK;
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_code = code;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CoursePackage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CoursePackage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CoursePackage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CoursePackageImpl coursePackageImpl = new CoursePackageImpl();

		coursePackageImpl.setCoursePackageId(getCoursePackageId());
		coursePackageImpl.setGroupId(getGroupId());
		coursePackageImpl.setCompanyId(getCompanyId());
		coursePackageImpl.setUserId(getUserId());
		coursePackageImpl.setUserName(getUserName());
		coursePackageImpl.setCreateDate(getCreateDate());
		coursePackageImpl.setModifiedDate(getModifiedDate());
		coursePackageImpl.setName(getName());
		coursePackageImpl.setCode(getCode());

		coursePackageImpl.resetOriginalValues();

		return coursePackageImpl;
	}

	@Override
	public int compareTo(CoursePackage coursePackage) {
		long primaryKey = coursePackage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CoursePackage)) {
			return false;
		}

		CoursePackage coursePackage = (CoursePackage)obj;

		long primaryKey = coursePackage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CoursePackageModelImpl coursePackageModelImpl = this;

		coursePackageModelImpl._originalCoursePackageId = coursePackageModelImpl._coursePackageId;

		coursePackageModelImpl._setOriginalCoursePackageId = false;

		coursePackageModelImpl._originalGroupId = coursePackageModelImpl._groupId;

		coursePackageModelImpl._setOriginalGroupId = false;

		coursePackageModelImpl._originalName = coursePackageModelImpl._name;

		coursePackageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CoursePackage> toCacheModel() {
		CoursePackageCacheModel coursePackageCacheModel = new CoursePackageCacheModel();

		coursePackageCacheModel.coursePackageId = getCoursePackageId();

		coursePackageCacheModel.groupId = getGroupId();

		coursePackageCacheModel.companyId = getCompanyId();

		coursePackageCacheModel.userId = getUserId();

		coursePackageCacheModel.userName = getUserName();

		String userName = coursePackageCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			coursePackageCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			coursePackageCacheModel.createDate = createDate.getTime();
		}
		else {
			coursePackageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			coursePackageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			coursePackageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		coursePackageCacheModel.name = getName();

		String name = coursePackageCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			coursePackageCacheModel.name = null;
		}

		coursePackageCacheModel.code = getCode();

		String code = coursePackageCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			coursePackageCacheModel.code = null;
		}

		return coursePackageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{coursePackageId=");
		sb.append(getCoursePackageId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", code=");
		sb.append(getCode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.ocms.course.model.CoursePackage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>coursePackageId</column-name><column-value><![CDATA[");
		sb.append(getCoursePackageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>code</column-name><column-value><![CDATA[");
		sb.append(getCode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CoursePackage.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CoursePackage.class
		};
	private long _coursePackageId;
	private long _originalCoursePackageId;
	private boolean _setOriginalCoursePackageId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _name;
	private String _originalName;
	private String _code;
	private long _columnBitmask;
	private CoursePackage _escapedModel;
}